package collector

import (
	model "data-plane/telemetry/model"
	"encoding/json"
	"log/slog"
	"time"
)

// VMCollector main collector (integrates all sub-collectors)
type VMCollector struct{}

// NewVMCollector initialize main collector
func NewVMCollector() *VMCollector {
	return &VMCollector{}
}

// Collect gathers all VM info and assembles into VMReport
func (c *VMCollector) Collect(pre string, logger *slog.Logger) (*model.VMReport, error) {
	// 1. Collect info from all dimensions
	cpuInfo, err := collectCPU()
	if err != nil {
		return nil, err
	}

	memoryInfo, err := collectMemory()
	if err != nil {
		return nil, err
	}

	diskInfo, err := collectDisk()
	if err != nil {
		return nil, err
	}

	networkInfo, err := collectNetwork()
	if err != nil {
		return nil, err
	}

	osInfo, err := collectOS()
	if err != nil {
		return nil, err
	}

	processInfo, err := collectProcess()
	if err != nil {
		return nil, err
	}

	link := collectLink()

	//hostname, _ := os.Hostname()

	queue, err := collectQueue()
	if err != nil {
		logger.Warn("Failed to get congestion info", slog.Any("err", err))
	}

	val := &model.VMReport{
		VMID:        "vm-" + networkInfo.PublicIP + "-001", // Fixed VMID (replace based on actual scenario)
		CollectTime: time.Now().UTC(),
		ReportID:    "", // Filled by server/reporter during reporting
		CPU:         cpuInfo,
		Memory:      memoryInfo,
		Disk:        diskInfo,
		Network:     networkInfo,
		OS:          osInfo,
		Process:     processInfo,
		Queue:       queue,
		Link:        link,
	}

	b, _ := json.Marshal(val)
	logger.Info("", slog.String("pre", pre), slog.String("report val", string(b)))

	// 2. Assemble VMReport (ReportID generated by reporter, left empty here)
	return val, nil
}
