port: "8080"
control_host: "http://127.0.0.1:8081"
local_base_dir: "/root/storage/"
gcp_service_account: "/root/gcp-service-account.json"

# SSH配置（远端文件读取用）
#ssh:
#  user: "root"
#  host: "192.168.1.20"
#  ssh_port: "22"
#  password: "your-ssh-password" # 替换为实际密码
#  remote_dir: "/home/matth/storage/"
#
#cred_file_source: "/home/matth/civil-honor-480405-e0-e62b994bbc27.json"
#bucket_name_source: "rigel-data"
#
#file_sys:
#  upload: "http://127.0.0.1:8081/api/v1/chunk/upload"
#  merge: "http://127.0.0.1:8081/api/v1/chunk/merge"
#
#cred_file: "/home/matth/civil-honor-480405-e0-e62b994bbc27.json"
#bucket_name: "rigel-data-1"