package model

import (
	"data-plane/probing"
	"time"
)

// VMReport is the core struct reported by the data plane to the control plane (all fields)
type VMReport struct {
	// Basic identifiers (required)
	VMID        string    `json:"vm_id"`        // VM unique ID (UUID/hostname+MAC, globally unique)
	CollectTime time.Time `json:"collect_time"` // Collection time (UTC, format: 2025-12-20T10:00:00Z)
	ReportID    string    `json:"report_id"`    // Single report record ID (UUID, generated by data plane / filled by control plane)

	// CPU info (required)
	CPU CPUInfo `json:"cpu"`

	// Memory info (required)
	Memory MemoryInfo `json:"memory"`

	// Disk info (optional, default root partition / system disk)
	Disk DiskInfo `json:"disk,omitempty"`

	// Network info (required, public IP is key field)
	Network NetworkInfo `json:"network"`

	// System basic info (optional)
	OS OSInfo `json:"os,omitempty"`

	// Process info (optional)
	Process ProcessInfo `json:"process,omitempty"`

	Queue QueueInfo `json:"queue"`

	Link []LinkInfo `json:"link"`
}

// CPUInfo CPU dimension info
type CPUInfo struct {
	PhysicalCore int     `json:"physical_core"`       // Physical core count (e.g. 2)
	LogicalCore  int     `json:"logical_core"`        // Logical core count (e.g. 4)
	Usage        float64 `json:"usage"`               // Overall CPU usage (%, 1 decimal place, e.g. 25.3)
	Load1Min     float64 `json:"load_1min,omitempty"` // 1-minute system load avg (optional, e.g. 0.8)
}

// MemoryInfo memory dimension info (unit: bytes)
type MemoryInfo struct {
	Total uint64  `json:"total"` // Total memory (e.g. 17179869184 = 16GB)
	Used  uint64  `json:"used"`  // Used memory
	Free  uint64  `json:"free"`  // Available memory
	Usage float64 `json:"usage"` // Memory usage rate (%, 1 decimal place, e.g. 60.5)
}

// DiskInfo disk dimension info (default root partition, unit: bytes)
type DiskInfo struct {
	Total uint64  `json:"total"` // Total partition size
	Used  uint64  `json:"used"`  // Used size
	Free  uint64  `json:"free"`  // Available size
	Usage float64 `json:"usage"` // Usage rate (%, 1 decimal place)
	Path  string  `json:"path"`  // Mount path (e.g. /, C:\)
}

// NetworkInfo network dimension info (public IP is core required field)
type NetworkInfo struct {
	PublicIP   string `json:"public_ip"`             // Public IP (required, "no-public-ip" if none, comma-separated for multiple)
	PrivateIP  string `json:"private_ip"`            // Private IP (e.g. 192.168.1.100, empty if none)
	PortCount  int    `json:"port_count"`            // Total occupied ports (TCP+UDP, 0 if none)
	TrafficIn  uint64 `json:"traffic_in,omitempty"`  // Inbound NIC traffic in 5s collection window (bytes, optional)
	TrafficOut uint64 `json:"traffic_out,omitempty"` // Outbound NIC traffic in 5s collection window (bytes, optional)
}

// OSInfo system basic info
type OSInfo struct {
	OSName    string `json:"os_name"`    // Operating system (e.g. Linux/Windows/macOS)
	KernelVer string `json:"kernel_ver"` // Kernel version (e.g. Linux 5.15.0-78-generic / Windows 10 22H2)
	Hostname  string `json:"hostname"`   // Hostname
	BootTime  int64  `json:"boot_time"`  // System boot timestamp (seconds, 0 if unknown)
}

// ProcessInfo process info
type ProcessInfo struct {
	ActiveCount int             `json:"active_count"` // Active process count (0 if none)
	TopCPU      []ProcessDetail `json:"top_cpu"`      // Top 3 CPU processes (pad with empty if fewer)
	TopMem      []ProcessDetail `json:"top_mem"`      // Top 3 memory processes (pad with empty if fewer)
}

// ProcessDetail process detail
type ProcessDetail struct {
	PID   int     `json:"pid"`   // Process ID (0 if unknown)
	Name  string  `json:"name"`  // Process name (e.g. nginx/java, empty if unknown)
	Usage float64 `json:"usage"` // Usage rate (%, 1 decimal place)
}

// ApiResponse standard API response wrapper
type ApiResponse struct {
	Code int         `json:"code"` // 200=success, 400=param error, 500=server error
	Msg  string      `json:"msg"`  // Message
	Data interface{} `json:"data"` // Business data: VMReport for reporting, filled VMReport for response
}

// QueueInfo queue / congestion info (fetched from proxy)
type QueueInfo struct {
	ActiveConnections int64   `json:"active_connections"` // Current active connections
	TotalMem          int64   `json:"total_mem"`          // Machine total memory (bytes)
	ProcessMem        int64   `json:"process_mem"`        // Current process memory usage (bytes)
	AvgCachePerConn   float64 `json:"avg_cache_per_conn"` // Average cache per connection (bytes)
	CacheUsageRatio   float64 `json:"cache_usage_ratio"`  // Cache usage ratio [0,1]
}

// LinkInfo link / path info (from probing results)
type LinkInfo struct {
	TargetIP       string            `json:"target_ip"`        // Target node IP
	Target         probing.ProbeTask `json:"target"`           // Probe task reference
	PacketLoss     float64           `json:"packet_loss"`      // Packet loss rate (percentage)
	WeightedCache  float64           `json:"weighted_cache"`   // Link cache status (optional)
	AverageLatency float64           `json:"average_latency"`  // Average latency (milliseconds)
	BandwidthUsage float64           `json:"bandwidth_usage"`  // Bandwidth utilization (optional, percentage)
}
